config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :expenses
  resources :labelings
  resources :labels
  resources :logins, only: %i[new create destroy]
  resources :users
end

app/models/label.rb
class Label < ApplicationRecord
  include Colorable

  belongs_to :user, inverse_of: :labels
  has_many :labelings, dependent: :destroy
  has_many :expenses, through: :labelings, source: :labelable, source_type: 'Expense', inverse_of: :labels
  has_many :incomes, through: :labelings, source: :labelable, source_type: 'Income', inverse_of: :labels

  validates :name, length: { maximum: 63 }, presence: true, uniqueness: { scope: :user_id }

  scope :expense, -> { joins(:expenses) }
  scope :income, -> { joins(:incomes) }
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[show edit update destroy]

  # GET /labels
  def index
    @labels = Label.all
  end

  # GET /labels/1
  def show; end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit; end

  # POST /labels
  def create
    @label = Label.new(label_params)

    if @label.save
      redirect_to label_url(@label)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /labels/1
  def update
    if @label.update(label_params)
      redirect_to label_url(@label)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /labels/1
  def destroy
    @label.destroy

    redirect_to labels_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_label
    @label = Label.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def label_params
    params.require(:label).permit(:name)
  end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, class: "contents") do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= label.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this label", label, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this label', edit_label_path(label), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/labels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing label</h1>

  <%= render "form", label: @label %>

  <%= link_to "Show this label", @label, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to labels", labels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/labels/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Labels</h1>
    <%= link_to 'New label', new_label_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="labels" class="min-w-full">
    <%= render @labels %>
  </div>
</div>

app/views/labels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New label</h1>

  <%= render "form", label: @label %>

  <%= link_to 'Back to labels', labels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/labels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @label %>

    <%= link_to 'Edit this label', edit_label_path(@label), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this label', label_path(@label), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to labels', labels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>