config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :expenses
  resources :labelings
  resources :labels
  resources :logins, only: %i[new create destroy]
  resources :users
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :label, inverse_of: :labelings
  belongs_to_polymorphic :labelable, allowed_classes: [Expense, Income], inverse_of: :labelings

  validates :label_id, uniqueness: { scope: :labelable_id, case_sensitive: false }
end

app/controllers/labelings_controller.rb
class LabelingsController < ApplicationController
  before_action :set_labeling, only: %i[show edit update destroy]

  # GET /labelings
  def index
    @labelings = Labeling.all
  end

  # GET /labelings/1
  def show; end

  # GET /labelings/new
  def new
    @labeling = Labeling.new
  end

  # GET /labelings/1/edit
  def edit; end

  # POST /labelings
  def create
    @labeling = Labeling.new(labeling_params)

    if @labeling.save
      redirect_to labeling_url(@labeling)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /labelings/1
  def update
    if @labeling.update(labeling_params)
      redirect_to labeling_url(@labeling)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /labelings/1
  def destroy
    @labeling.destroy

    redirect_to labelings_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_labeling
    @labeling = Labeling.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def labeling_params
    params.require(:labeling).permit(:user_id, :label_id, :expense_id)
  end
end

app/views/labelings/_form.html.erb
<%= form_with(model: labeling, class: "contents") do |form| %>
  <% if labeling.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(labeling.errors.count, "error") %> prohibited this labeling from being saved:</h2>

      <ul>
        <% labeling.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :label_id %>
    <%= form.text_field :label_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :expense_id %>
    <%= form.text_field :expense_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/labelings/_labeling.html.erb
<div id="<%= dom_id labeling %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= labeling.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Label:</strong>
    <%= labeling.label_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Expense:</strong>
    <%= labeling.expense_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this labeling", labeling, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this labeling', edit_labeling_path(labeling), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/labelings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing labeling</h1>

  <%= render "form", labeling: @labeling %>

  <%= link_to "Show this labeling", @labeling, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to labelings", labelings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/labelings/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Labelings</h1>
    <%= link_to 'New labeling', new_labeling_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="labelings" class="min-w-full">
    <%= render @labelings %>
  </div>
</div>

app/views/labelings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New labeling</h1>

  <%= render "form", labeling: @labeling %>

  <%= link_to 'Back to labelings', labelings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/labelings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @labeling %>

    <%= link_to 'Edit this labeling', edit_labeling_path(@labeling), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this labeling', labeling_path(@labeling), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to labelings', labelings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>